/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Alibaba.
 */
type ModelName
    = | "deepseek-r-1"
        | "deepseek-r-1-0528"
        | "deepseek-r-1-685b"
        | "deepseek-r-1-distill-qwen-1-5-b"
        | "deepseek-v-3"
        | "deepseek-v-3-1"
        | "deepseek-v-3-2"
        | "deepseek-v-3-2-exp"
        | "moonshot-kimi-k2-instruct";

export default ModelName;
