/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Anthropic.
 */
type ModelName
    = | "claude-haiku-3"
        | "claude-haiku-3-5"
        | "claude-haiku-4-5"
        | "claude-opus-3-(deprecated)"
        | "claude-opus-4"
        | "claude-opus-4-1"
        | "claude-opus-4-5"
        | "claude-sonnet-3-5-(deprecated)"
        | "claude-sonnet-3-7"
        | "claude-sonnet-4"
        | "claude-sonnet-4-5";

export default ModelName;
