/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Azure OpenAI.
 */
type ModelName
    = | "gpt-35-turbo-(0125)"
        | "gpt-35-turbo-(1106)"
        | "gpt-4-(turbo-2024-04-09)"
        | "gpt-4-o-(2024-05-13)"
        | "gpt-4-o-(2024-08-06)"
        | "gpt-4-o-(2024-11-20)"
        | "gpt-4-o-mini-(2024-07-18)"
        | "o-1-mini-(2024-09-12)"
        | "o-1-preview-(2024-09-12)";

export default ModelName;
