/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for DeepSeek.
 */
type ModelName = "deep-seek-v3-0324";

export default ModelName;
