/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Deep Infra.
 */
type ModelName
    = | "MiniMaxAI/MiniMax-M2"
        | "PaddlePaddle/PaddleOCR-VL-0.9B"
        | "Qwen/Qwen3-Coder-480B-A35B-Instruct"
        | "Qwen/Qwen3-Coder-480B-A35B-Instruct-Turbo"
        | "allenai/olmOCR-2-7B-1025"
        | "allenai/olmOCR-7B-0725-FP8"
        | "anthropic/claude-4-opus"
        | "anthropic/claude-4-sonnet"
        | "deepseek-ai/DeepSeek-OCR"
        | "deepseek-ai/DeepSeek-R1-0528-Turbo"
        | "deepseek-ai/DeepSeek-V3-0324-Turbo"
        | "deepseek-ai/DeepSeek-V3.1"
        | "deepseek-ai/DeepSeek-V3.1-Terminus"
        | "deepseek-ai/DeepSeek-V3.2"
        | "meta-llama/Llama-3.3-70B-Instruct"
        | "meta-llama/Llama-3.3-70B-Instruct-Turbo"
        | "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8"
        | "meta-llama/Llama-4-Maverick-17B-128E-Instruct-Turbo"
        | "meta-llama/Llama-4-Scout-17B-16E-Instruct"
        | "meta-llama/Llama-Guard-4-12B"
        | "mistralai/Devstral-Small-2507"
        | "mistralai/Mistral-Small-3.2-24B-Instruct-2506"
        | "moonshotai/Kimi-K2-Thinking"
        | "nvidia/Nemotron-3-Nano-30B-A3B"
        | "zai-org/GLM-4.5"
        | "zai-org/GLM-4.5V";

export default ModelName;
