/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for GitHub Models.
 */
type ModelName
    = | "about-github-models"
        | "ask-copilot-open"
        | "ask-copilot-select"
        | "github-models"
        | "optimizing-your-ai-powered-app-with-github-models"
        | "prototyping-with-ai-models"
        | "use-github-models";

export default ModelName;
