/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Google Partner.
 */
type ModelName
    = | "claude-3-5-haiku"
        | "claude-3-5-sonnet"
        | "claude-3-5-sonnet-v-2"
        | "claude-3-7-sonnet"
        | "claude-3-haiku"
        | "codestral-(25-01)"
        | "codestral-2"
        | "jamba-1-5-large"
        | "jamba-1-5-mini"
        | "mistral-large-(24-11)"
        | "mistral-medium-3"
        | "mistral-ocr-(25-05)"
        | "mistral-small-3-1-(25-03)"
        | "safety-classifiers"
        | "web-search";

export default ModelName;
