/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Google Vertex.
 */
type ModelName
    = | "code-gemma"
        | "embeddings-for-text"
        | "gemini-2-5-flash-image"
        | "gemini-2-5-flash-with-gemini-live-api"
        | "gemini-3-pro-image"
        | "gemma"
        | "gemma-2"
        | "gemma-3"
        | "gemma-3-n"
        | "imagen-3-for-editing-and-customization"
        | "imagen-3-for-fast-generation"
        | "imagen-3-for-generation"
        | "imagen-3-for-generation-001"
        | "imagen-3-for-generation-002"
        | "imagen-4-for-fast-generation"
        | "imagen-4-for-generation"
        | "imagen-4-for-ultra-generation"
        | "imagen-for-captioning-&-vqa"
        | "imagen-product-recontext-on-vertex-ai"
        | "med-gemma"
        | "multimodal-embeddings"
        | "pali-gemma"
        | "shield-gemma-2"
        | "t-5-gemma"
        | "tx-gemma"
        | "veo-2"
        | "veo-2-experimental"
        | "veo-2-generate"
        | "veo-2-preview"
        | "veo-3"
        | "veo-3-1-fast"
        | "veo-3-1-fast-preview"
        | "veo-3-1-generate"
        | "veo-3-1-generate-preview"
        | "veo-3-fast"
        | "veo-3-fast-preview"
        | "veo-3-generate"
        | "veo-3-generate-preview"
        | "veo-3-preview";

export default ModelName;
