/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Google.
 */
type ModelName
    = | "gemini-1-5-flash"
        | "gemini-1-5-flash-8b"
        | "gemini-1-5-pro"
        | "gemini-2-0-flash-lite"
        | "gemini-2-0-flash-preview-image-generation"
        | "gemini-2-5-flash"
        | "gemini-2-5-flash-lite"
        | "gemini-2-5-flash-native-audio"
        | "gemini-2-5-flash-preview-tts"
        | "gemini-2-5-pro-preview-tts"
        | "gemini-api-card-width"
        | "gemini-api-elevation-1-dp"
        | "gemini-api-elevation-3-dp"
        | "gemini-api-model-font"
        | "gemini-api-table-font-color";

export default ModelName;
