/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Groq.
 */
type ModelName
    = | "canopy"
        | "compound"
        | "compound-beta"
        | "compound-beta-mini"
        | "deepseek-r-1-distill-llama-70-b"
        | "gpt"
        | "kimi"
        | "llama"
        | "llama-3-1-8-b-instant"
        | "llama-3-3-70-b-versatile"
        | "meta-llama-llama-4-maverick-17-b-128-e-instruct"
        | "meta-llama-llama-4-scout-17-b-16-e-instruct"
        | "meta-llama-llama-guard-4-12-b"
        | "meta-llama-llama-prompt-guard-2-22-m"
        | "meta-llama-llama-prompt-guard-2-86-m"
        | "moonshotai-kimi-k-2-instruct"
        | "openai-gpt-oss-120-b"
        | "openai-gpt-oss-20-b"
        | "playai-tts"
        | "playai-tts-arabic"
        | "prompt"
        | "qwen-qwen-3-32-b"
        | "safety"
        | "whisper";

export default ModelName;
