/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Hugging Face.
 */
type ModelName
    = | "amazon-chronos-t-5-small"
        | "babelscape-rebel-large"
        | "context-labs-meta-llama-llama-3-2-3b-instruct-fp16"
        | "distilbert-distilgpt-2"
        | "dphn-dolphin-2-9-1-yi-1-5-34-b"
        | "facebook-bart-large-cnn"
        | "facebook-opt-125-m"
        | "gensyn-qwen-2-5-0-5b-instruct"
        | "google-gemma-3-1-b-it"
        | "google-t-5-gemma-b-b-prefixlm"
        | "google-t-5-t-5-small"
        | "meta-llama-llama-3-2-1b-instruct"
        | "openai-community-gpt-2"
        | "openai-community-gpt-2-large"
        | "qwen-qwen-2-5-1-5b-instruct"
        | "qwen-qwen-2-5-32b-instruct"
        | "qwen-qwen-2-5-3b-instruct"
        | "qwen-qwen-2-5-7b-instruct"
        | "qwen-qwen-2-5-coder-0-5b-instruct"
        | "qwen-qwen-2-5-vl-3b-instruct"
        | "qwen-qwen-2-5-vl-7b-instruct"
        | "qwen-qwen-3-0-6b"
        | "qwen-qwen-3-1-7b"
        | "qwen-qwen-3-4b"
        | "qwen-qwen-3-4b-base"
        | "qwen-qwen-3-4b-instruct-2507"
        | "qwen-qwen-3-8b"
        | "qwen-qwen-3-embedding-0-6b"
        | "qwen-qwen-3-next-80b-a3b-instruct"
        | "unslothai-1"
        | "vikhyatk-moondream-2";

export default ModelName;
