/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for inception.
 */
type ModelName = "mercury" | "mercury-2" | "mercury-coder" | "mercury-edit";

export default ModelName;
