/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Meta.
 */
type ModelName = "llama-3_3-70b-instruct" | "llama-3_3-8b-instruct" | "llama-4-maverick-17b-128e-instruct-fp8" | "llama-4-scout-17b-16e-instruct-fp8";

export default ModelName;
