/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Ollama Cloud.
 */
type ModelName
    = | "ollama/cogito-2.1:671b"
        | "ollama/deepseek-v3.1:671b"
        | "ollama/deepseek-v3.2"
        | "ollama/devstral-2:123b"
        | "ollama/devstral-small-2:24b"
        | "ollama/gemini-3-flash-preview"
        | "ollama/gemini-3-pro-preview"
        | "ollama/gemma3:12b"
        | "ollama/gemma3:27b"
        | "ollama/gemma3:4b"
        | "ollama/glm-4.6"
        | "ollama/glm-4.7"
        | "ollama/gpt-oss:120b"
        | "ollama/gpt-oss:20b"
        | "ollama/kimi-k2-thinking"
        | "ollama/kimi-k2:1t"
        | "ollama/minimax-m2"
        | "ollama/minimax-m2.1"
        | "ollama/ministral-3:14b"
        | "ollama/ministral-3:3b"
        | "ollama/ministral-3:8b"
        | "ollama/mistral-large-3:675b"
        | "ollama/nemotron-3-nano:30b"
        | "ollama/qwen3-coder:480b"
        | "ollama/qwen3-next:80b"
        | "ollama/qwen3-vl:235b"
        | "ollama/qwen3-vl:235b-instruct"
        | "ollama/rnj-1:8b";

export default ModelName;
