/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for ollama-cloud.
 */
type ModelName = "ollama/glm-5" | "ollama/kimi-k2.5" | "ollama/minimax-m2.5" | "ollama/qwen3-coder-next" | "ollama/qwen3.5:397b";

export default ModelName;
