/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for OpenAI.
 */
type ModelName
    = | "codex-mini-latest"
        | "gpt-3.5-turbo"
        | "gpt-4"
        | "gpt-4-32k"
        | "gpt-4-turbo"
        | "gpt-4.1"
        | "gpt-4.1-mini"
        | "gpt-4.1-nano"
        | "gpt-4o"
        | "gpt-4o-mini"
        | "o1"
        | "o1-mini"
        | "o1-preview"
        | "o3"
        | "o3-mini"
        | "o3-pro"
        | "o4-mini";

export default ModelName;
