/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all available AI model provider names.
 */
export type ProviderName =
    | "AIHubMix"
    | "Alibaba"
    | "Amazon Bedrock"
    | "Anthropic"
    | "Azure OpenAI"
    | "Cloudflare"
    | "Deep Infra"
    | "DeepSeek"
    | "Fireworks AI"
    | "GitHub Copilot"
    | "Google"
    | "Google Partner"
    | "Google Vertex"
    | "Groq"
    | "Hugging Face"
    | "Inference"
    | "Meta"
    | "Mistral"
    | "ModelScope"
    | "Ollama Cloud"
    | "OpenAI"
    | "OpenRouter"
    | "Requesty"
    | "Together AI"
    | "Upstage"
    | "V0"
    | "Venice"
    | "Vercel"
    | "Weights & Biases"
    | "XAI"
    | "cerebras"
    | "chutes"
    | "inception";

/**
 * Array of all available provider names.
 */
export const PROVIDER_NAMES: ReadonlyArray<ProviderName> = [
    "AIHubMix",
    "Alibaba",
    "Amazon Bedrock",
    "Anthropic",
    "Azure OpenAI",
    "Cloudflare",
    "Deep Infra",
    "DeepSeek",
    "Fireworks AI",
    "GitHub Copilot",
    "Google",
    "Google Partner",
    "Google Vertex",
    "Groq",
    "Hugging Face",
    "Inference",
    "Meta",
    "Mistral",
    "ModelScope",
    "Ollama Cloud",
    "OpenAI",
    "OpenRouter",
    "Requesty",
    "Together AI",
    "Upstage",
    "V0",
    "Venice",
    "Vercel",
    "Weights & Biases",
    "XAI",
    "cerebras",
    "chutes",
    "inception",
] as const;
