/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all available AI model provider names
 */
export type ProviderName = "Weights & Biases";

/**
 * Array of all available provider names
 */
export const PROVIDER_NAMES = ["Weights & Biases"] as const satisfies ReadonlyArray<ProviderName>;
