/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for V0.
 */
type ModelName
    = | "4-nwqv-0-zkit-3-b-9-v-6-h"
        | "5v0h3h13h14"
        | "classic-v-0"
        | "create-v-0-sdk-app"
        | "featuresv-0"
        | "logo-particles-v-0-aws-ad-fq-yl-ef-vd-c"
        | "pagev-0"
        | "product-home-enterprise-pricingv-0"
        | "what-can-you-do-with-v-0"
        | "what-makes-v-0-different"
        | "who-is-v-0-for"
        | "why-should-i-choose-v-0";

export default ModelName;
