/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for Weights & Biases.
 */
type ModelName
    = | "deepseek-ai-deep-seek-r1-0528"
        | "deepseek-ai-deep-seek-v3-0324"
        | "deepseek-ai-deep-seek-v3-1"
        | "meta-llama-llama-3-1-70b-instruct"
        | "meta-llama-llama-3-1-8b-instruct"
        | "meta-llama-llama-3-3-70b-instruct"
        | "meta-llama-llama-4-scout-17b-16e-instruct"
        | "microsoft-phi-4-mini-instruct"
        | "moonshotai-kimi-k2-instruct"
        | "open-pipe-qwen-3-14b-instruct"
        | "qwen-qwen-2-5-14b-instruct"
        | "qwen-qwen-3-235b-a22b-instruct-2507"
        | "qwen-qwen-3-235b-a22b-thinking-2507"
        | "qwen-qwen-3-coder-480b-a35b-instruct"
        | "zai-org-glm-4-5";

export default ModelName;
