/* Auto-generated file - do not edit manually
 * Generated by aggregate-providers.ts
 *
 * To regenerate this file, run: pnpm run aggregate
 */

/**
 * Union type of all model IDs for XAI.
 */
type ModelName = "grok-2-image-1212" | "grok-2-vision-1212" | "grok-3" | "grok-3-fast" | "grok-3-mini" | "grok-3-mini-fast" | "grok-4-0709";

export default ModelName;
