packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - nx
  - oxc-resolver
  - protobufjs
  - puppeteer
  - sharp
  - unrs-resolver
