packages:
  - web
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - nx
  - oxc-resolver
  - protobufjs
  - puppeteer
  - rs-module-lexer
  - sharp
  - unrs-resolver

overrides:
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  js-yaml@<3.14.2: '>=3.14.2'
  next@>=15.0.0 <15.2.3: '>=15.2.3'
  preact@>=10.27.0 <10.27.3: '>=10.27.3'
  tmp@<=0.2.3: '>=0.2.4'
