packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - nx
  - oxc-resolver
  - protobufjs
  - puppeteer
  - sharp
  - unrs-resolver

overrides:
  next@>=15.0.0 <15.2.3: '>=15.2.3'
