packages:
  - web
  - packages/*

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - nx
  - oxc-resolver
  - protobufjs
  - puppeteer
  - rs-module-lexer
  - sharp
  - unrs-resolver

overrides:
  diff@<8.0.3: '>=8.0.3'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  h3@<=1.15.4: '>=1.15.5'
  js-yaml@<3.14.2: '>=3.14.2'
  next@>=15.0.0 <15.2.3: '>=15.2.3'
  preact@>=10.27.0 <10.27.3: '>=10.27.3'
  tmp@<=0.2.3: '>=0.2.4'
  undici@<6.23.0: '>=6.23.0'
  undici@>=7.0.0 <7.18.2: '>=7.18.2'
  vite: 8.0.0-beta.7
