name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@58bf3316370d2f360af64c7154a4b5043ebb6131" # main
        with:
            target-repo: "anolilab/ai-models"
            onboarding-lead: "prisis"
