name: "AlloAllo"

on: # yamllint disable-line rule:truthy
    issues:
        types:
            - "opened"
    pull_request_target:
        branches:
            - "main"
        types:
            - "opened"
            - "closed"

jobs:
    allo-allo:
        uses: "anolilab/workflows/.github/workflows/allo-allo.yml@a54753412124efe9ffdf4564c568134c09a7363d" # main
        with:
            target-repo: "anolilab/ai-models"
            onboarding-lead: "prisis"
