name: "Cleanup caches by a branch"

on: # yamllint disable-line rule:truthy
    pull_request:
        types:
            - "closed"
    workflow_dispatch: # yamllint disable-line rule:empty-values

jobs:
    cleanup-branch-cache:
        uses: "anolilab/workflows/.github/workflows/cleanup-branch-cache.yml@b7c2014dc8b1f022a340111874e6c13346e17598" # main
        with:
            target-repo: "anolilab/ai-models"
