name: "Lock inactive issues and pull requests"

on: # yamllint disable-line rule:truthy
    schedule:
        - cron: "0 * * * *"
    workflow_dispatch: # yamllint disable-line rule:empty-values

jobs:
    lock-closed:
        uses: "anolilab/workflows/.github/workflows/lock-closed.yml@58bf3316370d2f360af64c7154a4b5043ebb6131" # main
        with:
            target-repo: "anolilab/ai-models"
