name: "Semantic Pull Request"

on: # yamllint disable-line rule:truthy
    pull_request_target:
        types:
            - "opened"
            - "reopened"
            - "edited"
            - "synchronize"
    merge_group: # yamllint disable-line rule:empty-values

jobs:
    stale-issues:
        uses: "anolilab/workflows/.github/workflows/semantic-pull-request.yml@d7d84717329a45c2b5ffbda19ae76d8604f61c00" # main
        with:
            target-repo: "anolilab/ai-models"
